name: Generate Space Shooter Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Tambahkan blok ini untuk memberikan izin eksplisit
      contents: write
    steps:
      - name: generate-gh-space-shooter
        uses: czl9707/gh-space-shooter@v2.0.2
        with:
          github_user_name: ${{ github.repository_owner }}
          # Kita gunakan output branch yang lebih simpel
          output_branch: output
          output_directory: dist

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
